set(GRAPHICS_SRCS
        ${MODULES}/Graphics/DebugOpenGL.hpp
        ${MODULES}/Graphics/Pipeline.cpp
        ${MODULES}/Graphics/Pipeline.hpp
        ${MODULES}/Graphics/PostProcessEffect.hpp
        ${MODULES}/Graphics/PostProcessQuad.cpp
        ${MODULES}/Graphics/PostProcessQuad.hpp
        ${MODULES}/Graphics/Primitives.cpp
        ${MODULES}/Graphics/Primitives.hpp
        ${MODULES}/Graphics/RenderTarget.cpp
        ${MODULES}/Graphics/RenderTarget.hpp
        ${MODULES}/Graphics/Shader.cpp
        ${MODULES}/Graphics/Shader.hpp
        ${MODULES}/Graphics/ShaderProgram.cpp
        ${MODULES}/Graphics/ShaderProgram.hpp
        ${MODULES}/Graphics/Texture2D.cpp
        ${MODULES}/Graphics/Texture2D.hpp
        ${MODULES}/Graphics/Vertex.hpp
        ${MODULES}/Graphics/VertexArray.cpp
        ${MODULES}/Graphics/VertexArray.hpp
        ${MODULES}/Graphics/VertexAttribute.hpp
        # Post processing effects
        ${MODULES}/Graphics/Effects/Tonemapper.hpp
        ${MODULES}/Graphics/Effects/Tonemapper.cpp
)